/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated.app'
import { Route as AuthenticatedResultsRouteImport } from './routes/_authenticated.results'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesCommunityGrowthRouteImport } from './routes/services.community-growth'
import { Route as ServicesIcoMarketingRouteImport } from './routes/services.ico-marketing'
import { Route as ServicesInvestorOutreachRouteImport } from './routes/services.investor-outreach'
import { Route as ServicesSeoForCryptoRouteImport } from './routes/services.seo-for-crypto'
import { Route as ServicesTokenomicsDesignRouteImport } from './routes/services.tokenomics-design'
import { Route as ServicesWhitepaperWritingRouteImport } from './routes/services.whitepaper-writing'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResultsRoute = AuthenticatedResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCommunityGrowthRoute = ServicesCommunityGrowthRouteImport.update({
  id: '/community-growth',
  path: '/community-growth',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesIcoMarketingRoute = ServicesIcoMarketingRouteImport.update({
  id: '/ico-marketing',
  path: '/ico-marketing',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesInvestorOutreachRoute =
  ServicesInvestorOutreachRouteImport.update({
    id: '/investor-outreach',
    path: '/investor-outreach',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesSeoForCryptoRoute = ServicesSeoForCryptoRouteImport.update({
  id: '/seo-for-crypto',
  path: '/seo-for-crypto',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesTokenomicsDesignRoute =
  ServicesTokenomicsDesignRouteImport.update({
    id: '/tokenomics-design',
    path: '/tokenomics-design',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesWhitepaperWritingRoute =
  ServicesWhitepaperWritingRouteImport.update({
    id: '/whitepaper-writing',
    path: '/whitepaper-writing',
    getParentRoute: () => ServicesRoute,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRouteWithChildren
  '/app': typeof AuthenticatedAppRoute
  '/results': typeof AuthenticatedResultsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/services/community-growth': typeof ServicesCommunityGrowthRoute
  '/services/ico-marketing': typeof ServicesIcoMarketingRoute
  '/services/investor-outreach': typeof ServicesInvestorOutreachRoute
  '/services/seo-for-crypto': typeof ServicesSeoForCryptoRoute
  '/services/tokenomics-design': typeof ServicesTokenomicsDesignRoute
  '/services/whitepaper-writing': typeof ServicesWhitepaperWritingRoute
  '/services/': typeof ServicesIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRoute
  '/results': typeof AuthenticatedResultsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/services/community-growth': typeof ServicesCommunityGrowthRoute
  '/services/ico-marketing': typeof ServicesIcoMarketingRoute
  '/services/investor-outreach': typeof ServicesInvestorOutreachRoute
  '/services/seo-for-crypto': typeof ServicesSeoForCryptoRoute
  '/services/tokenomics-design': typeof ServicesTokenomicsDesignRoute
  '/services/whitepaper-writing': typeof ServicesWhitepaperWritingRoute
  '/services': typeof ServicesIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/results': typeof AuthenticatedResultsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/services/community-growth': typeof ServicesCommunityGrowthRoute
  '/services/ico-marketing': typeof ServicesIcoMarketingRoute
  '/services/investor-outreach': typeof ServicesInvestorOutreachRoute
  '/services/seo-for-crypto': typeof ServicesSeoForCryptoRoute
  '/services/tokenomics-design': typeof ServicesTokenomicsDesignRoute
  '/services/whitepaper-writing': typeof ServicesWhitepaperWritingRoute
  '/services/': typeof ServicesIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/services'
    | '/app'
    | '/results'
    | '/settings'
    | '/auth/callback'
    | '/services/community-growth'
    | '/services/ico-marketing'
    | '/services/investor-outreach'
    | '/services/seo-for-crypto'
    | '/services/tokenomics-design'
    | '/services/whitepaper-writing'
    | '/services/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/app'
    | '/results'
    | '/settings'
    | '/auth/callback'
    | '/services/community-growth'
    | '/services/ico-marketing'
    | '/services/investor-outreach'
    | '/services/seo-for-crypto'
    | '/services/tokenomics-design'
    | '/services/whitepaper-writing'
    | '/services'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/services'
    | '/_authenticated/app'
    | '/_authenticated/results'
    | '/_authenticated/settings'
    | '/auth/callback'
    | '/services/community-growth'
    | '/services/ico-marketing'
    | '/services/investor-outreach'
    | '/services/seo-for-crypto'
    | '/services/tokenomics-design'
    | '/services/whitepaper-writing'
    | '/services/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/results': {
      id: '/_authenticated/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AuthenticatedResultsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/community-growth': {
      id: '/services/community-growth'
      path: '/community-growth'
      fullPath: '/services/community-growth'
      preLoaderRoute: typeof ServicesCommunityGrowthRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ico-marketing': {
      id: '/services/ico-marketing'
      path: '/ico-marketing'
      fullPath: '/services/ico-marketing'
      preLoaderRoute: typeof ServicesIcoMarketingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/investor-outreach': {
      id: '/services/investor-outreach'
      path: '/investor-outreach'
      fullPath: '/services/investor-outreach'
      preLoaderRoute: typeof ServicesInvestorOutreachRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/seo-for-crypto': {
      id: '/services/seo-for-crypto'
      path: '/seo-for-crypto'
      fullPath: '/services/seo-for-crypto'
      preLoaderRoute: typeof ServicesSeoForCryptoRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/tokenomics-design': {
      id: '/services/tokenomics-design'
      path: '/tokenomics-design'
      fullPath: '/services/tokenomics-design'
      preLoaderRoute: typeof ServicesTokenomicsDesignRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/whitepaper-writing': {
      id: '/services/whitepaper-writing'
      path: '/whitepaper-writing'
      fullPath: '/services/whitepaper-writing'
      preLoaderRoute: typeof ServicesWhitepaperWritingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedResultsRoute: typeof AuthenticatedResultsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedResultsRoute: AuthenticatedResultsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ServicesRouteChildren {
  ServicesCommunityGrowthRoute: typeof ServicesCommunityGrowthRoute
  ServicesIcoMarketingRoute: typeof ServicesIcoMarketingRoute
  ServicesInvestorOutreachRoute: typeof ServicesInvestorOutreachRoute
  ServicesSeoForCryptoRoute: typeof ServicesSeoForCryptoRoute
  ServicesTokenomicsDesignRoute: typeof ServicesTokenomicsDesignRoute
  ServicesWhitepaperWritingRoute: typeof ServicesWhitepaperWritingRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesCommunityGrowthRoute: ServicesCommunityGrowthRoute,
  ServicesIcoMarketingRoute: ServicesIcoMarketingRoute,
  ServicesInvestorOutreachRoute: ServicesInvestorOutreachRoute,
  ServicesSeoForCryptoRoute: ServicesSeoForCryptoRoute,
  ServicesTokenomicsDesignRoute: ServicesTokenomicsDesignRoute,
  ServicesWhitepaperWritingRoute: ServicesWhitepaperWritingRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRouteWithChildren,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
